<?php

namespace ContainerC5craWW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4ymPt5MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ymPt5M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ymPt5M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EventController::delete' => ['privates', '.service_locator.91kLpXo', 'get_ServiceLocator_91kLpXoService', true],
            'App\\Controller\\EventController::edit' => ['privates', '.service_locator.91kLpXo', 'get_ServiceLocator_91kLpXoService', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController::join' => ['privates', '.service_locator.BRcXwux', 'get_ServiceLocator_BRcXwuxService', true],
            'App\\Controller\\EventController::new' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController::show' => ['privates', '.service_locator.89sRwg8', 'get_ServiceLocator_89sRwg8Service', true],
            'App\\Controller\\EventUserController::index' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventUserController::show' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\HomepageController::default' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\HomepageController::noUserShowEvent' => ['privates', '.service_locator.89sRwg8', 'get_ServiceLocator_89sRwg8Service', true],
            'App\\Controller\\HomepageController::noUserindex' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\HomepageController::userShowEvent' => ['privates', '.service_locator.89sRwg8', 'get_ServiceLocator_89sRwg8Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController::promoteUser' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\EventController:delete' => ['privates', '.service_locator.91kLpXo', 'get_ServiceLocator_91kLpXoService', true],
            'App\\Controller\\EventController:edit' => ['privates', '.service_locator.91kLpXo', 'get_ServiceLocator_91kLpXoService', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController:join' => ['privates', '.service_locator.BRcXwux', 'get_ServiceLocator_BRcXwuxService', true],
            'App\\Controller\\EventController:new' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController:show' => ['privates', '.service_locator.89sRwg8', 'get_ServiceLocator_89sRwg8Service', true],
            'App\\Controller\\EventUserController:index' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventUserController:show' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\HomepageController:default' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\HomepageController:noUserShowEvent' => ['privates', '.service_locator.89sRwg8', 'get_ServiceLocator_89sRwg8Service', true],
            'App\\Controller\\HomepageController:noUserindex' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\HomepageController:userShowEvent' => ['privates', '.service_locator.89sRwg8', 'get_ServiceLocator_89sRwg8Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController:promoteUser' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\EventController::delete' => '?',
            'App\\Controller\\EventController::edit' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Controller\\EventController::join' => '?',
            'App\\Controller\\EventController::new' => '?',
            'App\\Controller\\EventController::show' => '?',
            'App\\Controller\\EventUserController::index' => '?',
            'App\\Controller\\EventUserController::show' => '?',
            'App\\Controller\\HomepageController::default' => '?',
            'App\\Controller\\HomepageController::noUserShowEvent' => '?',
            'App\\Controller\\HomepageController::noUserindex' => '?',
            'App\\Controller\\HomepageController::userShowEvent' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::promoteUser' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\EventController:delete' => '?',
            'App\\Controller\\EventController:edit' => '?',
            'App\\Controller\\EventController:index' => '?',
            'App\\Controller\\EventController:join' => '?',
            'App\\Controller\\EventController:new' => '?',
            'App\\Controller\\EventController:show' => '?',
            'App\\Controller\\EventUserController:index' => '?',
            'App\\Controller\\EventUserController:show' => '?',
            'App\\Controller\\HomepageController:default' => '?',
            'App\\Controller\\HomepageController:noUserShowEvent' => '?',
            'App\\Controller\\HomepageController:noUserindex' => '?',
            'App\\Controller\\HomepageController:userShowEvent' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:promoteUser' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
