<?php

namespace ContainerC5craWW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvent3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BRcXwux.App\Entity\Event' shared service.
     *
     * @return \App\Entity\Event
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BRcXwux": it references class "App\\Entity\\Event" but no such service exists.');
    }
}
