<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDchcMAV\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDchcMAV/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDchcMAV.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDchcMAV\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDchcMAV\App_KernelProdContainer([
    'container.build_hash' => 'DchcMAV',
    'container.build_id' => 'aeeef6e1',
    'container.build_time' => 1675727573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDchcMAV');
