<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGbB7sB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGbB7sB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGbB7sB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGbB7sB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGbB7sB\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGbB7sB',
    'container.build_id' => '67dded64',
    'container.build_time' => 1677530806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGbB7sB');
