<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxIJlJj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxIJlJj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxIJlJj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxIJlJj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxIJlJj\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxIJlJj',
    'container.build_id' => '44360b8e',
    'container.build_time' => 1674842397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxIJlJj');
