<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2By4yc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2By4yc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN2By4yc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN2By4yc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN2By4yc\App_KernelDevDebugContainer([
    'container.build_hash' => 'N2By4yc',
    'container.build_id' => '5ac256c5',
    'container.build_time' => 1676226240,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2By4yc');
