<?php

namespace ContainerUcAS3Dy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__B5Q7JwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..B5Q7Jw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..B5Q7Jw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator..B5Q7Jw.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator..B5Q7Jw": it references class "App\\Entity\\Event" but no such service exists.'],
            'objectManager' => ['privates', '.errored..service_locator..B5Q7Jw.Doctrine\\Persistence\\ObjectManager', NULL, 'Cannot autowire service ".service_locator..B5Q7Jw": it references interface "Doctrine\\Persistence\\ObjectManager" but no such service exists. You should maybe alias this interface to the existing "doctrine.orm.default_entity_manager" service.'],
        ], [
            'event' => 'App\\Entity\\Event',
            'objectManager' => 'Doctrine\\Persistence\\ObjectManager',
        ]);
    }
}
